Truncate table Silver_error.Appointment
Truncate table Silver_error.Bed
Truncate table Silver_error.Billing
Truncate table Silver_error.Department
Truncate table Silver_error.Doctor
Truncate table Silver_error.MedicalStock
Truncate table Silver_error.MedicalTest
Truncate table Silver_error.medicine_patient
Truncate table Silver_error.Patient
Truncate table Silver_error.PatientTest
Truncate table Silver_error.Room
Truncate table Silver_error.SatisfactionScore
Truncate table Silver_error.Staff
Truncate table Silver_error.Supplier
Truncate table Silver_error.Surgery
